export const FIREBASE_ADMIN_MODULE_OPTIONS = 'FIREBASE_ADMIN_MODULE_OPTIONS';
export const FIREBASE_ADMIN_NAME = 'FIREBASE_ADMIN_NAME';
export const FIREBASE_ADMIN_INJECT = 'FIREBASE_ADMIN_INJECT';
export const FIREBASE_ADMIN_CONFIG = 'FIREBASE_ADMIN_CONFIG';
export const FIREBASE_ADMIN_AUTH_STRATEGY = 'FIREBASE_ADMIN_AUTH_STRATEGY';

export const FIREBASE_USER_METADATA = 'FIREBASE_USER_METADATA';
export const FIREBASE_APP_ROLES_DECORATOR = 'ROLES';
